/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import java.io.DataInputStream;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;
import java.net.URLEncoder;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author swetha kantheti
 */

class t1 extends Thread{
    
}
public class forumthrd extends javax.swing.JFrame{

    /**
     * Creates new form forumthrd
     */
    
    String s="----";int i=0;forumthread f=new forumthread("");
   // forumthread ff=new forumthread("");

     

//     
//     void com(){
//        
//        try {
//            String charset = "UTF-8";
//                        String param1 = "gops";
//                        String query = String.format("?q=%s", 
//                                    URLEncoder.encode(param1, charset));
//                        URL url = new URL("http://localhost:8084/app2servlet/abcd");
//                        HttpURLConnection con = null;
//            try {
//                con = (HttpURLConnection) url.openConnection();
//            } catch (IOException ex) {
//                Logger.getLogger(forumthread.class.getName()).log(Level.SEVERE, null, ex);
//            }
//                        con.setRequestProperty("Accept-Charset", charset);
//
//                        con.setDoInput(true);
//                        con.setDoOutput(true);
//       //		 con.setUseCaches(false);
//                        con.setRequestProperty("Content-Type", "application/x-www-form-urlencoded");
//       //
//       //		 DataOutputStream printout = new DataOutputStream(con.getOutputStream());
//       //
//       //		 // This is the POST 
//       //		 String content ="email=jad939933@hotmail.com&pass=577383";
//       //
//       //
//       //		 printout.writeBytes(content);
//       //		 printout.flush();
//       //		 printout.close();
//
//
//
//
//
//                        DataInputStream input = null;
//            try {
//                input = new DataInputStream(con.getInputStream());
//            } catch (IOException ex) {
//                Logger.getLogger(forumthread.class.getName()).log(Level.SEVERE, null, ex);
//            }
//                        String str;
//                        //Read the response
//                        while (null != ((str = input.readLine()))) {
//                        //System.out.println(str);
//                            if(str.contains("<h1>")){
//                                int a=str.indexOf(">");
//                                int b=str.lastIndexOf("<");
//                                str=(String) str.subSequence(a+2,b);
//                                s=s+"\n"+str;
//                            }
//                        }
//                        input.close();
//        } catch (UnsupportedEncodingException ex) {
//            Logger.getLogger(forumthread.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (MalformedURLException ex) {
//            Logger.getLogger(forumthread.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (IOException ex) {
//            Logger.getLogger(forumthread.class.getName()).log(Level.SEVERE, null, ex);
//        }
//       // System.out.println(s);
//        jTextArea1.setText(s);
//         
//     }
    public forumthrd() {
        initComponents();
         
        
//      s=i+"";
//         jTextArea1.setText(s);
//        jTextArea1.setEditable(false);//i++;
       f.start();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextField1.setText("Enter your mesage");

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(forumthrd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(forumthrd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(forumthrd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(forumthrd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new forumthrd().setVisible(false);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    

     
}
