/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import java.io.IOException;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author swetha kantheti
 */
public class LogInPage extends javax.swing.JFrame {

    /**
     * Creates new form LoginPage
     */
    public LogInPage() {
        initComponents();
        if(new netconnection().connection()){
                this.setVisible(false);
          //  new SimpleSwingBrowser1().main(null);
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPCS = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabelPassWord = new javax.swing.JLabel();
        jLabelPassWord1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);

        jLabelPCS.setBackground(new java.awt.Color(255, 255, 255));
        jLabelPCS.setFont(new java.awt.Font("Freestyle Script", 1, 36)); // NOI18N
        jLabelPCS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPCS.setText("Predictable Convergent Solutions");
        getContentPane().add(jLabelPCS);
        jLabelPCS.setBounds(450, 210, 530, 120);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(680, 330, 210, 30);

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(680, 410, 210, 30);

        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(720, 480, 100, 30);

        jLabelPassWord.setBackground(new java.awt.Color(153, 153, 153));
        jLabelPassWord.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabelPassWord.setText("         Username:");
        getContentPane().add(jLabelPassWord);
        jLabelPassWord.setBounds(480, 330, 140, 30);

        jLabelPassWord1.setBackground(new java.awt.Color(153, 153, 153));
        jLabelPassWord1.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabelPassWord1.setText("         Password:");
        getContentPane().add(jLabelPassWord1);
        jLabelPassWord1.setBounds(480, 410, 140, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/a.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-10, 0, 1380, 770);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        String uname=jTextField1.getText();
        String pwd=jPasswordField1.getText();
        Connection con;
        try {
            con = DatabaseConnection.dbConnection();
            PreparedStatement pst=con.prepareStatement("Select emp_id,password from registration where emp_id=? and password=?");
            pst.setString(1,uname);
            pst.setString(2,pwd);
            ResultSet rs=pst.executeQuery();
            if(rs.next()){System.out.println(uname+"------");
                this.setVisible(false);
        //        Home.main(uname);
                netconnection nc=new netconnection();
                if(nc.connection()){
                    Home.main(uname);
 //----------------------------------------------------------------------
                    RatingThread r=new RatingThread(uname);
                      r.start();
                   forumthread f=new forumthread(uname);
                     f.start();
                     commentthread c=new commentthread(uname);
                    c.start();
//                   UploadStartUP up=new UploadStartUP();
//                   up.start();
                     ListFiles l=new ListFiles();
                     l.start();
//--------------------------------------------------------------------------                
                 //    new SimpleSwingBrowser1().main(null);
                }
                else{
                     Home.main(uname);
 //                   BrowserEmbed.main(uname);
                }
            }
            else{
                this.setVisible(false);
                LogInPage.main(null);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(LogInPage.class.getName()).log(Level.SEVERE, null, ex);
        }  
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogInPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogInPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogInPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogInPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
            
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogInPage().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelPCS;
    private javax.swing.JLabel jLabelPassWord;
    private javax.swing.JLabel jLabelPassWord1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
